USE [master]
GO

/****** Object:  Database [HouseRental]    Script Date: 5/23/2022 4:20:17 PM ******/
CREATE DATABASE [HouseRental]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HouseRental', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HouseRental.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HouseRental_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HouseRental_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HouseRental].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HouseRental] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HouseRental] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HouseRental] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HouseRental] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HouseRental] SET ARITHABORT OFF 
GO

ALTER DATABASE [HouseRental] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HouseRental] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HouseRental] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HouseRental] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HouseRental] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HouseRental] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HouseRental] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HouseRental] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HouseRental] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HouseRental] SET  ENABLE_BROKER 
GO

ALTER DATABASE [HouseRental] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HouseRental] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HouseRental] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HouseRental] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HouseRental] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HouseRental] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HouseRental] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HouseRental] SET RECOVERY FULL 
GO

ALTER DATABASE [HouseRental] SET  MULTI_USER 
GO

ALTER DATABASE [HouseRental] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HouseRental] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HouseRental] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HouseRental] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HouseRental] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HouseRental] SET  READ_WRITE 
GO

